name: "🐛 Bug Report"
description: "Report a bug"
labels: ["bug"]
body:
  - type: textarea
    id: details
    attributes:
      label: "Bug Details"
      description: "What happened? (Expected vs Actual)"
      placeholder: "Describe the bug and how to reproduce it..."
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: "Logs / Screenshots"
      description: "Paste error logs or drag-and-drop screenshots."
