name: "🛠️ Enhancement"
description: "Refine an existing feature"
labels: ["enhancement"]
body:
  - type: input
    id: component
    attributes:
      label: "Component"
      placeholder: "e.g. blog-ui, infra-ansible"
    validations:
      required: true
  - type: textarea
    id: improvement
    attributes:
      label: "Improvement"
      description: "What should be improved?"
    validations:
      required: true
