name: "🚀 Feature Request"
description: "Propose a new idea"
labels: ["enhancement"]
body:
  - type: textarea
    id: goal
    attributes:
      label: "Goal"
      description: "What do you want to achieve?"
      placeholder: "Describe the feature and why it's needed..."
    validations:
      required: true
  - type: textarea
    id: implementation
    attributes:
      label: "Implementation Idea"
      description: "Any thoughts on how to build this?"
